const age = 12;
console.log(age);
const name = "Yaroslav";
console.log(name);
const isStudent = true;
console.log(isStudent);
const myString = "ᵛᶤʳ ᶠᵒʳᵗᵘᶰᵃᵉ ˢᵘᵐ ᵉᵗ ᶜᵃᵘᵈᵃᵐ ᵉᶤᵘˢ ᶰᵘᶰᶜ ᵖʳᵉʰᵉᶰᵈᵃᵐ";
console.log(myString);
let myNumber = 5;
myNumber = myNumber + 10;
console.log(myNumber);
const myNull = null;
console.log(myNull);
const userName = prompt("Введіть ваше ім’я");
alert("Ваше ім’я: " + userName);
console.log(typeof userName);
let userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log(userAnswer);
alert( "Увага! Дія може бути небезпечною.");
const doYouWantContinue = confirm("Ви впевнені, що хочете продовжити?");